name: Spellcheck

on: push

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Spell check
        run: |
          pip install codespell    
          codespell -S deps,_build,.git,.elixir_ls -L Domin -r "(?<!@)\\b[a-zA-Z0-9_'-]+\\b"
